dataset:
  name: delany
  path: molbench/core/data/datasets/delaney-processed.csv
  smiles_col:
  - smiles
  split:
    method: random
    seed: 42
    test_ratio: 0.1
    train_ratio: 0.7
    val_ratio: 0.2
  target_cols:
  - ESOL predicted log solubility in mols per litre
  task_type: regression
evaluation:
  extra_metrics:
  - Pearson_r
  - F1_macro
  output_dir: ./results
  save_plots: true
  visualization: true
featurizer:
  name: ecfp
  params:
    n_bits: 2048
    radius: 2
models:
- hyperopt_config: test/random_forest_regressor.json
  name: RandomForestRegressor
  protocol: sklearn
  type: sklearn
optimization:
  n_iter: 30
system:
  cache: true
  cache_dir: ./.molbench_cache
  n_jobs: 1
  verbose: true
